# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('rfc', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('aPaterno', models.CharField(max_length=50)),
                ('aMaterno', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=50)),
                ('razonSocial', models.CharField(max_length=50)),
                ('giro', models.CharField(max_length=50)),
            ],
        ),
    ]
