# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balofi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=15)),
                ('tamanio', models.CharField(max_length=15)),
                ('numeroDePiezas', models.IntegerField(default=1)),
                ('entradaOSalida', models.IntegerField(default=0)),
                ('fechaMovimiento', models.DateField()),
                ('caducidad', models.DateField()),
                ('cliente', models.CharField(max_length=13)),
            ],
        ),
    ]
