# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balofi', '0002_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
