# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balofi', '0003_productos_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False)),
                ('rfcEmisor', models.CharField(max_length=13)),
                ('nombreEmisor', models.CharField(max_length=50)),
                ('direccionEmisor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('rfcReceptor', models.CharField(max_length=13)),
                ('nombreReceptor', models.CharField(max_length=50)),
                ('direccionReceptor', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('IVA', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cliente', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
